apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-kubernetes
    test: sh
  name: hello-kubernetes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-kubernetes
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-kubernetes
        test: sh
    spec:
      containers:
      - image: paulbouwer/hello-kubernetes:1.10.1
        imagePullPolicy: Always
        name: whoami
        resources:
          limits:
            cpu: 500m
            memory: 250Mi
          requests:
            cpu: 500m
            memory: 250Mi
        env:
          FOO: "123"
        envFrom:
        - configMapRef:
            name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: 
        runAsUser: 1000
      terminationGracePeriodSeconds: 30
