apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: whoami
    test: sh
  name: whoami
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: whoami
        test: sh
    spec:
      containers:
      - image: 198443438542.dkr.ecr.eu-west-1.amazonaws.com/whoami:latest
        imagePullPolicy: Always
        name: whoami
        resources:
          limits:
            cpu: 100m
            memory: 5Gi
          requests:
            cpu: 100m
            memory: 5Gi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
