apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: whoami
    test: sh
  name: whoami
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: whoami
        test: sh
        hello: world
        env: 2
    spec:
      containers:
      - image: traefik/whoami:latest
        imagePullPolicy: Always
        name: whoami
        resources:
          limits:
            cpu: 500m
            memory: 250Mi
          requests:
            cpu: 500m
            memory: 250Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
