apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-kubernetes
    test: sh
    kaluzaplatform.net/mi-scale-in: "true"
  name: hello-kubernetes
  annotations:
    replicaPath: "env1.deployment.really_long_reference_to_go_over_sixty_three_chars.replicaCount"
spec:
  replicas: {{ $.Values.deployment.really_long_reference_to_go_over_sixty_three_chars.replicaCount }}
  selector:
    matchLabels:
      app: hello-kubernetes
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-kubernetes
        test: sh
    spec:
      containers:
      - image: paulbouwer/hello-kubernetes:1.10.1
        imagePullPolicy: Always
        name: whoami
        resources:
          limits:
            cpu: 500m
            memory: 250Mi
          requests:
            cpu: 500m
            memory: 250Mi
        env:
        - name: FOO
          value: "678"
        envFrom:
        - configMapRef:
            name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: 
        runAsUser: 1000
      terminationGracePeriodSeconds: 30
