apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cron-scaledobject
spec:
  scaleTargetRef:
    name: hello-kubernetes
  triggers:
  - type: cron
    metadata:
      timezone: Asia/Kolkata
      start: 10 * * * *
      end: 15 * * * *
      desiredReplicas: "0"