apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: hello-kubernetes-statefulset
    kaluzaplatform.net/mi-scale-in: "true"
    tags.datadog.com/team: "jaws"
  name: hello-kubernetes-statefulset
  annotations:
    replicaPath: "statefulset.replicaCount"
spec:
  serviceName: "hello-kubernetes-statefulset"
  replicas: {{ .Values.statefulset.replicaCount }}
  selector:
    matchLabels:
      app: hello-kubernetes-statefulset
  template:
    metadata:
      labels:
        app: hello-kubernetes-statefulset
        test: sh
    spec:
      containers:
      - image: paulbouwer/hello-kubernetes:1.10.1
        imagePullPolicy: Always
        name: whoami
        resources:
          limits:
            cpu: 500m
            memory: 250Mi
          requests:
            cpu: 500m
            memory: 250Mi
        env:
        - name: FOO
          value: "678"
        envFrom:
        - configMapRef:
            name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 1000
      terminationGracePeriodSeconds: 30
